// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: example/configs/conf.proto

package configs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Db            *DBConfig              `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Redis         *RedisConfig           `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	Server        *ServerConfig          `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_example_configs_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_example_configs_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_example_configs_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetDb() *DBConfig {
	if x != nil {
		return x.Db
	}
	return nil
}

func (x *Config) GetRedis() *RedisConfig {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Config) GetServer() *ServerConfig {
	if x != nil {
		return x.Server
	}
	return nil
}

type DBConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dsn           string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBConfig) Reset() {
	*x = DBConfig{}
	mi := &file_example_configs_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBConfig) ProtoMessage() {}

func (x *DBConfig) ProtoReflect() protoreflect.Message {
	mi := &file_example_configs_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBConfig.ProtoReflect.Descriptor instead.
func (*DBConfig) Descriptor() ([]byte, []int) {
	return file_example_configs_conf_proto_rawDescGZIP(), []int{1}
}

func (x *DBConfig) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

type ServerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_example_configs_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_example_configs_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_example_configs_conf_proto_rawDescGZIP(), []int{2}
}

func (x *ServerConfig) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ServerConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RedisConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisConfig) Reset() {
	*x = RedisConfig{}
	mi := &file_example_configs_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisConfig) ProtoMessage() {}

func (x *RedisConfig) ProtoReflect() protoreflect.Message {
	mi := &file_example_configs_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisConfig.ProtoReflect.Descriptor instead.
func (*RedisConfig) Descriptor() ([]byte, []int) {
	return file_example_configs_conf_proto_rawDescGZIP(), []int{3}
}

func (x *RedisConfig) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RedisConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RedisConfig) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

var File_example_configs_conf_proto protoreflect.FileDescriptor

const file_example_configs_conf_proto_rawDesc = "" +
	"\n" +
	"\x1aexample/configs/conf.proto\x12\x0egonfig.example\"\x9b\x01\n" +
	"\x06Config\x12(\n" +
	"\x02db\x18\x01 \x01(\v2\x18.gonfig.example.DBConfigR\x02db\x121\n" +
	"\x05redis\x18\x02 \x01(\v2\x1b.gonfig.example.RedisConfigR\x05redis\x124\n" +
	"\x06server\x18\x03 \x01(\v2\x1c.gonfig.example.ServerConfigR\x06server\"\x1c\n" +
	"\bDBConfig\x12\x10\n" +
	"\x03dsn\x18\x01 \x01(\tR\x03dsn\"6\n" +
	"\fServerConfig\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"M\n" +
	"\vRedisConfig\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02dbB3Z1github.com/soyacen/gonfig/example/configs;configsb\x06proto3"

var (
	file_example_configs_conf_proto_rawDescOnce sync.Once
	file_example_configs_conf_proto_rawDescData []byte
)

func file_example_configs_conf_proto_rawDescGZIP() []byte {
	file_example_configs_conf_proto_rawDescOnce.Do(func() {
		file_example_configs_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_configs_conf_proto_rawDesc), len(file_example_configs_conf_proto_rawDesc)))
	})
	return file_example_configs_conf_proto_rawDescData
}

var file_example_configs_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_example_configs_conf_proto_goTypes = []any{
	(*Config)(nil),       // 0: gonfig.example.Config
	(*DBConfig)(nil),     // 1: gonfig.example.DBConfig
	(*ServerConfig)(nil), // 2: gonfig.example.ServerConfig
	(*RedisConfig)(nil),  // 3: gonfig.example.RedisConfig
}
var file_example_configs_conf_proto_depIdxs = []int32{
	1, // 0: gonfig.example.Config.db:type_name -> gonfig.example.DBConfig
	3, // 1: gonfig.example.Config.redis:type_name -> gonfig.example.RedisConfig
	2, // 2: gonfig.example.Config.server:type_name -> gonfig.example.ServerConfig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_example_configs_conf_proto_init() }
func file_example_configs_conf_proto_init() {
	if File_example_configs_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_configs_conf_proto_rawDesc), len(file_example_configs_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_configs_conf_proto_goTypes,
		DependencyIndexes: file_example_configs_conf_proto_depIdxs,
		MessageInfos:      file_example_configs_conf_proto_msgTypes,
	}.Build()
	File_example_configs_conf_proto = out.File
	file_example_configs_conf_proto_goTypes = nil
	file_example_configs_conf_proto_depIdxs = nil
}
