// Code generated by protoc-gen-gonfig. DO NOT EDIT.

package configs

import (
	context "context"
	gonfig "github.com/soyacen/gonfig"
	resource "github.com/soyacen/gonfig/resource"
	proto "google.golang.org/protobuf/proto"
	atomic "sync/atomic"
)

var (
	_Config atomic.Value
)

func init() {
	_Config.Store(&Config{})
}

func LoadConfig(ctx context.Context, dsn string) error {
	conf, err := gonfig.Load[*Config](ctx, dsn)
	if err != nil {
		return err
	}
	_Config.Store(conf)
	return nil
}

func WatchConfig(ctx context.Context, dsn string, errFunc resource.ErrFunc) (resource.StopFunc, error) {
	stopFunc, err := gonfig.Watch[*Config](ctx, dsn, func(conf *Config) { _Config.Store(conf) }, errFunc)
	if err != nil {
		return nil, err
	}
	return stopFunc, nil
}

func GetConfig() *Config {
	return proto.Clone(_Config.Load().(*Config)).(*Config)
}

func GetDb() *DBConfig {
	return proto.Clone(_Config.Load().(*Config).GetDb()).(*DBConfig)
}

func GetRedis() *RedisConfig {
	return proto.Clone(_Config.Load().(*Config).GetRedis()).(*RedisConfig)
}

func GetServer() *ServerConfig {
	return proto.Clone(_Config.Load().(*Config).GetServer()).(*ServerConfig)
}
