// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: configs/conf.proto

package configs

import (
	_ "github.com/soyacen/gonfig/proto/gonfig"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LEO_RUN_ENV   string                 `protobuf:"bytes,1,opt,name=LEO_RUN_ENV,json=LEORUNENV,proto3" json:"LEO_RUN_ENV,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvConfig) Reset() {
	*x = EnvConfig{}
	mi := &file_configs_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvConfig) ProtoMessage() {}

func (x *EnvConfig) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvConfig.ProtoReflect.Descriptor instead.
func (*EnvConfig) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{0}
}

func (x *EnvConfig) GetLEO_RUN_ENV() string {
	if x != nil {
		return x.LEO_RUN_ENV
	}
	return ""
}

type JSONFileConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONFileConfig) Reset() {
	*x = JSONFileConfig{}
	mi := &file_configs_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONFileConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONFileConfig) ProtoMessage() {}

func (x *JSONFileConfig) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONFileConfig.ProtoReflect.Descriptor instead.
func (*JSONFileConfig) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{1}
}

func (x *JSONFileConfig) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *JSONFileConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type YAMLFileConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,4,opt,name=db,proto3" json:"db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YAMLFileConfig) Reset() {
	*x = YAMLFileConfig{}
	mi := &file_configs_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YAMLFileConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YAMLFileConfig) ProtoMessage() {}

func (x *YAMLFileConfig) ProtoReflect() protoreflect.Message {
	mi := &file_configs_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YAMLFileConfig.ProtoReflect.Descriptor instead.
func (*YAMLFileConfig) Descriptor() ([]byte, []int) {
	return file_configs_conf_proto_rawDescGZIP(), []int{2}
}

func (x *YAMLFileConfig) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *YAMLFileConfig) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *YAMLFileConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *YAMLFileConfig) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

var File_configs_conf_proto protoreflect.FileDescriptor

const file_configs_conf_proto_rawDesc = "" +
	"\n" +
	"\x12configs/conf.proto\x12\x12leo.gonfig.example\x1a\x1cleo/gonfig/annotations.proto\"1\n" +
	"\tEnvConfig\x12\x1e\n" +
	"\vLEO_RUN_ENV\x18\x01 \x01(\tR\tLEORUNENV:\x04\xa8\xb6\"\x01\">\n" +
	"\x0eJSONFileConfig\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port:\x04\xa8\xb6\"\x01\"p\n" +
	"\x0eYAMLFileConfig\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x04 \x01(\x05R\x02db:\x04\xa8\xb6\"\x01B2Z0github.com/soyacen/gonfig/example/configs;configsb\x06proto3"

var (
	file_configs_conf_proto_rawDescOnce sync.Once
	file_configs_conf_proto_rawDescData []byte
)

func file_configs_conf_proto_rawDescGZIP() []byte {
	file_configs_conf_proto_rawDescOnce.Do(func() {
		file_configs_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configs_conf_proto_rawDesc), len(file_configs_conf_proto_rawDesc)))
	})
	return file_configs_conf_proto_rawDescData
}

var file_configs_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_configs_conf_proto_goTypes = []any{
	(*EnvConfig)(nil),      // 0: leo.gonfig.example.EnvConfig
	(*JSONFileConfig)(nil), // 1: leo.gonfig.example.JSONFileConfig
	(*YAMLFileConfig)(nil), // 2: leo.gonfig.example.YAMLFileConfig
}
var file_configs_conf_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_configs_conf_proto_init() }
func file_configs_conf_proto_init() {
	if File_configs_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configs_conf_proto_rawDesc), len(file_configs_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configs_conf_proto_goTypes,
		DependencyIndexes: file_configs_conf_proto_depIdxs,
		MessageInfos:      file_configs_conf_proto_msgTypes,
	}.Build()
	File_configs_conf_proto = out.File
	file_configs_conf_proto_goTypes = nil
	file_configs_conf_proto_depIdxs = nil
}
